nf-validation plugin for input samplesheet
genomic-medicine-sweden/metaval pull request #12
Opened 2024-02-08 13:39 UTC by LilyAnderssonLee

Close issues https://github.com/genomic-medicine-sweden/meta-val/issues/3 https://github.com/genomic-medicine-sweden/meta-val/issues/5

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/metaval/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/metaval _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-02-14 09:01 UTC, sofstam requested changes
Nice 🎉  A few suggestions :)

2024-02-14 09:01 UTC, sofstam commented on assets/.gitattributes
I think it would help to be able to see how the output of diamond, kraken2 and centrifuge looks like.

2024-02-14 09:01 UTC, sofstam commented on assets/samplesheet_v2.csv
What is the difference between `samplesheet_v1.csv` and `samplesheet_v2.csv`? Shall it just be named `samplesheet.csv`?

2024-02-14 09:01 UTC, sofstam commented on assets/samplesheet_v1.csv
A suggestion with names in the header:

kraken2_classifiedout -> kraken2_result
centrifuge_out -> centrifuge_report

2024-02-14 09:01 UTC, sofstam commented on assets/schema_input.json
> +                "exists": true,
Do we need all those? I think Illumina and Nanopore are enough.

2024-02-14 09:01 UTC, sofstam commented on assets/schema_input.json
> +                "errorMessage": "FastQ file for short reads 1, long reads or merged pair-end reads must be provided from bowtie2 or minimap2 unmapped read against the human genome, cannot contain spa
```suggestion
                "errorMessage": "FastQ file for short reads 1, long reads or merged pair-end reads must be provided from bowtie2 or minimap2 unmapped reads against the human genome, cannot contain spaces and must have extension '.fq.gz' or '.fastq.gz'."
```

2024-02-14 09:01 UTC, sofstam commented on assets/schema_input.json
> +                "errorMessage": "FastQ file for short reads 1, long reads or merged pair-end reads must be provided from bowtie2 or minimap2 unmapped read against the human genome, cannot contain spa
Where in the samplesheet would a merged pair-end reads be provided?

2024-02-14 09:01 UTC, sofstam commented on assets/schema_input.json
> +                "errorMessage": "The file contains the taxid and sequences ID."
```suggestion
                "errorMessage": "Kraken2 classification results must be provided."
```

2024-02-14 09:01 UTC, sofstam commented on assets/schema_input.json
> +                "errorMessage": "Centrifuge result file must be provided, and it should contains eight columns: readID, seqID, taxID, score, 2ndBestScore, hitLength, queryLength, numMatches."
```suggestion
                "errorMessage": "Centrifuge result file must be provided and it should contain eight columns: readID, seqID, taxID, score, 2ndBestScore, hitLength, queryLength, numMatches."
```

2024-02-14 09:01 UTC, sofstam commented on assets/schema_input.json
> +                "errorMessage": "Diamond classification result should be provided."
```suggestion
                "errorMessage": "Diamond classification results should be provided."
```

2024-02-16 14:32 UTC, LilyAnderssonLee commented on assets/.gitattributes
Sure. I can add this part.

2024-02-19 08:15 UTC, LilyAnderssonLee commented on assets/samplesheet_v2.csv
samplesheet_v1.csv contains the results of taxprofiler test data, while samplesheet_v2.csv contains the results of taxprofiler full test data. 
The difference is that there are too few classification results in taxprofiler test data, making it less ideal for meta-validation. However, the advantage of samplesheet_v1.csv is the small size of files, which could be helpful in CI tests in the future. Therefore, I would like to keep both for now and will update this part later on.

2024-02-19 08:27 UTC, LilyAnderssonLee commented on assets/schema_input.json
> +                "exists": true,
Yes we are using Illumina ad Nanopore. Those information was copied from `taxprofiler`. I guess it doesn't hurt to keep them.

2024-02-19 08:30 UTC, LilyAnderssonLee commented on assets/schema_input.json
> +                "errorMessage": "FastQ file for short reads 1, long reads or merged pair-end reads must be provided from bowtie2 or minimap2 unmapped read against the human genome, cannot contain spa
It would be placed in the column `fastq_1`.

2024-02-19 15:39 UTC, sofstam commented on assets/samplesheet_v2.csv
Sounds good then

2024-02-19 15:41 UTC, sofstam commented on assets/samplesheet_v1.csv
Is this being added now?

2024-02-19 15:42 UTC, sofstam commented on assets/schema_input.json
> +                "exists": true,
I would not mind removing them if it does not break the pipeline.

2024-02-20 07:17 UTC, LilyAnderssonLee commented on assets/samplesheet_v1.csv
Yes

2024-02-20 07:18 UTC, LilyAnderssonLee commented on assets/schema_input.json
> +                "exists": true,
Ok then only Illumina and Nanopore will be kept.

2024-02-27 14:21 UTC, LilyAnderssonLee commented
Can I merge it by ignoring the lint errors and the fix them later? @sofstam

2024-02-27 14:36 UTC, sofstam commented
Let's fix the linting later.

2024-02-27 15:01 UTC, LilyAnderssonLee commented
Can you approve it?

2024-02-27 15:04 UTC, sofstam approved these changes

2024-02-27 15:33 UTC, merged